apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: todo-mysql-db
spec:
  serviceName: "todo-mysql-db"
  replicas: 1
  selector:
    matchLabels:
      app: todo-mysql-db
  template:
    metadata:
      labels:
        app: todo-mysql-db
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "yourpassword"
        - name: MYSQL_DATABASE
          value: "TodoDb"
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: todo-mysql-db
spec:
  selector:
    app: todo-mysql-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
